### PR TITLE
324 deeper auth integration

### PR DESCRIPTION
**Pull request by WickyNilliams**
### What is the context of this PR?
Adds deeper authentication integration. Specifically:

* display's name in header
* identifies users with full story (when built with `REACT_APP_USE_FULLSTORY="true"`)
* supply user's name to API on creation of questionnaire
* display "created by" in questionnaires list

### How to review 

Review code, run tests, play with app

### CODE REVIEW

**Comment by WickyNilliams** [comment]
[Deeper authentication integration](https://trello.com/c/g11m6BHp/324-deeper-authentication-integration)

**Comment by hamishtaplin** [comment]
Can we tidy this up?

screenshot 2018-01-18 12 00 07

**Comment by hamishtaplin** [comment]
Icon/text aren't aligned centrally

screenshot 2018-01-18 12 05 22

**Comment by samiwel** [comment]
Now that we're moving over to email authentication by default, wonder if it makes sense to default to disable auth in development mode for better DX?

**Comment by WickyNilliams** [comment]
@samiwel i think it's better if we "dog food" what the users are doing. Otherwise we might miss issues with auth. You only need to sign in once, so not a lot of hassle for dev

**Pull request merged**
