### PR TITLE
JSON schemata improvements

### PR DESCRIPTION
**Pull request by iwootten**
### What is the context of this PR?

Introduced routing, repeated/conditional element rules to schemata to allow questionnaires to be created including them.

### How to review 
Start the eq-author app and attempt to save a survey that includes/doesn't include routing and repeated/conditional element rules e.g. the ones within eq-survey-runner/app/data.

### Who worked on the PR

@iwootten

### CODE REVIEW

**Comment by collisdigital** [comment]
Can this be merged?

**Comment by warrenbailey** [comment]
There appears to be a problem with the author application at the minute, which means I can't test this PR.

I'll sort that and then I'll come back to this and merge it.

**Comment by warrenbailey** [comment]
I think this could do with some tests. It would be good to add the following:

1. Submitting a valid schema with no special rules
2. Submitting a schema with routing rules
3. Submitting a schema with conditional display
4. Submitting a schema with repeating elements
5. Submitting an invalid schema

**Comment by warrenbailey** [comment]
This change set is re-introducing the qBuilder folder (could be a git rebase issue?). We definitely don't want that folder.  @jenniferedwards can you remove it?

**Comment by jjeane** [comment]
Yeah apologies, will do now

**Comment by warrenbailey** [comment]
LGTM 👍

**Pull request merged**
