### PR TITLE
add eslint rules and fix all violations

### PR DESCRIPTION
**Pull request by WickyNilliams**
### What is the context of this PR?
This PR adds an extensive set of ESLint rules which enforce coding style and help avoid many common JS pitfalls. This PR also fixes up any code that was in violation of those rules. 

The CI build will now fail if code is not fully linted.

### How to review 
Run `yarn install` and then `yarn lint`, ensure no errors are reported. Ensure you're happy with the rules that have been set.

Descriptions of rules can be found here:
* http://eslint.org/docs/rules/
* https://github.com/yannickcr/eslint-plugin-react#list-of-supported-rules

### CODE REVIEW

**Comment by WickyNilliams** [comment]
[Linting (3)](https://trello.com/c/iTn8wAc4/13-linting-3)

**Comment by hamishtaplin** [comment]
@WickyNilliams Worth adding a section in the readme?

Otherwise, this is GTG 👍

**Comment by hamishtaplin** [comment]
Getting a warning:

screenshot 2017-05-18 10 20 01

**Comment by WickyNilliams** [comment]
Yeah just noticed that... Fixed now

**Pull request merged**
