### PR TITLE
Migrations fix

### LINKED ISSUE #63: Author always complains about unapplied migrations
### Expected behaviour

Django starts up with no errors.

### Actual behaviour

Django always starts with:

> You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

### PR DESCRIPTION
**Pull request by iwootten**
### What is the context of this PR?
Updated the migrations to reflect current state of models in app and failing tests. Fixes #63.

### How to review 
Start the app and see if django complains about unapplied migrations.

- [ ] Do all commits have sensible commit messages?
- [ ] Is all new code unit tested?
- [ ] Are there integration tests if needed?
- [ ] Is there sufficient logging?
- [ ] Is there documentation or is the code self-describing?

### Who worked on the PR

@iwootten

### CODE REVIEW

**Comment by collisdigital** [comment]
Is there a general knowledge/update/process that needs to be understand in future to ensure this doesn't occur again (i.e. what to do when the model changes steps?)

**Comment by iwootten** [comment]
Possibly - basically if the model changes and migrations have yet to be applied, django will complain on startup. This model change (a non-nullable foreign key) has crept in as part of the schemata test changes, though I'm not sure why?

We could possibly perform a travis check to see if there are migration issues before PR's are accepted?

**Comment by dhilton** [comment]
This looks good to me - I'm a little worried we may have to destroy and recreate the preprod environment off the back of this fix but we need to have this fix.

**Comment by iwootten** [comment]
Are you able to evaluate which migrations have been applied in the preprod django db?

**Comment by dhilton** [comment]
All of them up to this change - so the migrations on master are automatically run.

**Comment by iwootten** [comment]
Is that a problem then, given there's only one migration that will be applied on top of the ones on preprod?

As a wider question, can a schema exist without it's schema meta? If so, the new migration file is not actually necessary and the original model change would need reverting.

**Pull request merged**
