### PR TITLE
Bug - Building with node 10

### PR DESCRIPTION
**Pull request by tgandrews**
### What is the context of this PR?
Upgrade firebase which had the dependency on the old version of grpc which was failing to build on node 10.

### How to review 
1. Ensure CI passes
1. Ensure it works locally with node 10.

### CODE REVIEW

**Comment by tgandrews** [comment]
Snyk is complaining about a transient dependency having a security vulnerability. But AFAICT they are not going to resolve it https://github.com/isaacs/chownr/issues/14

So I think we should ignore this in synk.

**Comment by tgandrews** [comment]
[Building author on node 10](https://trello.com/c/MeNr8OTr/735-building-author-on-node-10)

**Comment by SamGodwin2** [comment]
Is it worth updating the .nvmrc file to `lts/dubnium`?

**Comment by tgandrews** [comment]
@samiwel @SamGodwin2 I updated the `nvmrc` and `Dockerfile`.

**Pull request merged**
