### PR TITLE
Fix Tab rendering in prod

### PR DESCRIPTION
**Pull request by hamishtaplin**
## Changes

Fixes issue with non-rendering tabs in production build.

- better usage of displayName property to check child component type
- fixed styling issue with sidebar

## How to test

- run `yarn build`
- cd into `build` folder
- `python -m SimpleHTTPServer 8000` to spin up a server
- check tabs render as expected

### CODE REVIEW

**Comment by WickyNilliams** [comment]
I wonder if we should swap out custom implementation for a third party one? I've used this before and it worked well - fully accessible, and keyboard navigable https://github.com/reactjs/react-tabs

**Comment by hamishtaplin** [comment]
[Continuous Integration (1)](https://trello.com/c/zHcQ1y9Y/16-continuous-integration-1)

**Comment by hamishtaplin** [comment]
@WickyNilliams My issue with using third party components is that they force you into a certain way of doing things. For example, the method of styling would be different from the rest of the app if we used that.

**Comment by hamishtaplin** [comment]
@samiwel no, sorry too many changes in here. it was the implementation of using "displayName" as it was being obfuscated in prod.

https://github.com/ONSdigital/eq-author/pull/103/files#diff-8bb7228fecd81101876fa6bb572bd844L46

**Pull request merged**
