### PR TITLE
Refactor basename check into environment variable.

### PR DESCRIPTION
**Pull request by samiwel**
### What is the context of this PR?
This PR aims to leverage the Webpack environment configuration to determine if `basename` should be set between development and production.
During the build script, the `BASE_NAME` environment variable is set for 'production' builds.
The Webpage config defaults to an empty base name whilst in development mode.
The code which uses the basename has been refactored so as to not require the environment check.

### How to review 
Ensure that base name is configured appropriately for development and production builds.
Advise on any improvements to how I'm handling config in this PR.

### CODE REVIEW

**Comment by hamishtaplin** [comment]
@samiwel the basename seems to be causing issues on ghp at the moment, eg. clicking the "create" button takes you `https://onsdigital.github.io/eq-author/#/eq-author/create`. Does this PR fix this too?

**Comment by WickyNilliams** [comment]
That, to me, suggests we don't actually need a base path since we switched to hash routing?

**Comment by samiwel** [comment]
I think browserHistory routing was preferred but I read somewhere that it didn't play too nicely with GitHub pages.

**Comment by WickyNilliams** [comment]
Browser history is a little pointless without server-side rendering, or a server that knows to catch all requests and return the same result for any path

**Comment by WickyNilliams** [comment]
[Environment-specific vars (1)](https://trello.com/c/kqaSU38a/25-environment-specific-vars-1)

**Pull request merged**
