### PR TITLE
Initial creation of superuser

### PR DESCRIPTION
**Pull request by weapdiv-david**
### Changes

Creates an initial superuser account based on environment variables provided by terraform

### How to test
1) Ensure the environment variables are present within the elasticbeanstalk environment
2) Checkout this branch
3) Run eb deploy
4) Visit `/admin` on the newly deployed application
5) Login with the credentials supplied by terraform
6) ???
7) Profit!!!!

### Who can test

Anyone except @weapdiv-david

### CODE REVIEW

**Comment by warrenbailey** [comment]
Needs rebasing.

What does step 6 & 7 mean?

**Comment by weapdiv-david** [comment]
I haven't figured out step six

**Comment by dhilton** [comment]
@warrenbailey @LJBabbage  https://en.wikipedia.org/wiki/Gnomes_(South_Park)

**Comment by warrenbailey** [comment]
This needs to be run first https://github.com/ONSdigital/eq-terraform/pull/39

**Comment by warrenbailey** [comment]
Are you missing a file from the commit? I get a 404 for /admin?

screen shot 2016-06-21 at 08 34 32 3


👎

**Comment by warrenbailey** [comment]
It does work, I just figured out the url is `/admin/` and not `/admin` as documented in the PR

**Comment by warrenbailey** [comment]
LGTM 👍

**Pull request merged**
