### PR TITLE
Standardize bucket names

### PR DESCRIPTION
**Pull request by warrenbailey**
### Changes
Renaming the schema bucket environment variable so that it matches the survey runner one.

### How to test
1. Run this branch
2. Check the application still works

### Who can test
Anyone apart from @warrenbailey

### CODE REVIEW

**Comment by weapdiv-david** [comment]
This didn't work for me although I am having problems with the author app generally.  Can we go through this together?

**Comment by warrenbailey** [comment]
It doesn't change any functionality just the environment variable name (which doesn't need to be set locally) so it should work. Happy to go through it together, sounds like your author application might not be set up correctly.

**Comment by weapdiv-david** [comment]
After trying to figure out what the unhelpful error message I was getting with this most of the day (between meetings , anyway) I think it's an issue either with the node build script or the documentation...

In any case, running `npm run compile` did the compilation and allowed me to run the app locally where I couldn't before.

Happy to merge this, once it's been rebased

**Comment by warrenbailey** [comment]
Rebasing

**Pull request merged**
