### PR TITLE
Update readme and bash scripts

### PR DESCRIPTION
**Pull request by hamishtaplin**
### What is the context of this PR?

Our current readme and run_app script can be improved to improve developer experience.

### CODE REVIEW

**Comment by hamishtaplin** [comment]
This needs some love from the rest of the team, I've cleaned it up as much as I can but the section on deployment in particular needs some contributions.

**Comment by iwootten** [comment]
For me, this could do with something at the start of the readme explaining the structure of the app. i.e that it's a django REST app/react and that the frontend needs to be built prior to starting. 

Doesn't the npm compile addition to run_app mean it'll always compile on startup? Wouldn't build_app.sh be a better name for that script? The only step that needs to run post compile is runserver isn't it?

**Comment by warrenbailey** [comment]
Rebasing to master and adding the missing sections. I think this could be merged now, it's much better than it was.

**Comment by weapdiv-david** [comment]
LGTM :+1:

**Pull request merged**
