### PR TITLE
Digeq x angular prototype

### PR DESCRIPTION
**Pull request by weapdiv-david**
**What**

Rewritten question builder using angular.js

**How to test**

1) Create a survey and a new questionnaire
2) Drag and drop elements from the 'Question Types' area into the main area on the left
3) Drag and drop elements from the main area to the bin
4) Complete the dragged forms and verify the debug json is poplated below
5) Save your work
6) Reload the page and verify your changes were saved

**Who can test**

Anybody except @weapdiv-david and @LJBabbage 

**Still outstanding**

Several CSS bugs which will be fixed when the latest UI changes are applied

### CODE REVIEW

**Comment by warren-methods** [comment]
The Angular.js code looks good and I like where this pull request is going, but it doesn't feel quite finished to me. I've found the following issues:

1] The save button on the questionnaire builder works but nothing happens to inform the user it has been successful.
2] Dropping a multiple choice question on to it's answers causes the question to disappear.
3] Pulling a multiple choice answer out of it's question and into it's a slot designed for a question causes the previous page to be loaded into the middle of the questionnaire builder (very odd - see screenshot)
3] A JSON object is being rendered at the bottom of the questionnaire builder page (obviously don't want this in the production server)

I'm going to leave this up to @dhilton to choose whether we merge as is and fix later, or fix these issues now.

Overall though, it's pretty impressive, good work guys :+1: 

![screenshot from 2015-10-14 08 48 56]
(https://cloud.githubusercontent.com/assets/14093825/10477724/7dae2f0a-7250-11e5-891d-de279b53e84e.png)

**Comment by alexmorris** [comment]
Currently unusable in Safari - Drag and Drop is not working at all  - maybe some insight here.

http://caniuse.com/#feat=dragndrop

**Comment by alexmorris** [comment]
Actually just tested on Chrome and Firefox, broken on both... hmm

**Comment by warren-methods** [comment]
Tested and the drag and drop bugs no longer exist :+1:

**Pull request merged**
